inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance

AllCops:
  Exclude:
    - 'examples/*'
    - 'tasks/test.rake'
    - 'tmp/**/*'
  TargetRubyVersion: 2.4

# Tables are nice
Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
  EnforcedLastArgumentHashStyle: ignore_implicit

# Don't force lonely closing parentheses
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

# Multi-line method calls should be simply indented. Aligning them makes it
# even harder to keep a sane line length.
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Multi-line assignment should be simply indented. Aligning them makes it even
# harder to keep a sane line length.
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

# Force consistent spacing independent of block contents
Layout/SpaceBeforeBlockBraces:
  EnforcedStyleForEmptyBraces: space

# This cop gives bad advice
Lint/AmbiguousBlockAssociation:
  Enabled: false

# Allow if (foo = get_foo) style
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

Metrics/BlockLength:
  Exclude:
    - 'test/**/*' # Test describe blocks can be any size
    - '*.gemspec' # Gem spec blocks can be any size

# Be lenient with line length
Metrics/LineLength:
  Max: 95
  Exclude:
    - 'test/**/*'

# Allow and/or for control flow only
Style/AndOr:
  EnforcedStyle: conditionals

# Prefer actual numerics
Style/NumericPredicate:
  EnforcedStyle: comparison

# Use older RuboCop default
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()

# Allow explicit return with multiple return values
Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Do not commit to use of interpolation
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Prefer symbols to look like symbols
Style/SymbolArray:
  EnforcedStyle: brackets

# Project-specific configuration goes here.

# GObject has a lot of accessor method starting with get_ or set_
Naming/AccessorMethodName:
  Enabled: false

# GirFFI uses a gir_ffi-something naming scheme.
Naming/FileName:
  Enabled: false

# TODO: See about has_ and have_
Naming/PredicateName:
  ForbiddenPrefixes:
    - is_

# In tests, we want to do this to be more clear
Performance/FixedSize:
  Exclude:
    - 'test/**/*.rb'

# Accessors are only trivial if they match the ivar name.
# Also, allow accessors with ? in the name.
Style/TrivialAccessors:
  ExactNameMatch: true
  AllowPredicates: true
