AllCops:
  Exclude:
    - 'examples/*'
    - 'tasks/**/*.rake'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - Rakefile
    - gir_ffi.gemspec

# Allow if (foo = get_foo) style
Lint/AssignmentInCondition:
  AllowSafeAssignment: true

# Require lines to fit in pull requests.
Metrics/LineLength:
  Max: 92

# In tests, we want to do this to be more clear
Performance/FixedSize:
  Exclude:
    - 'test/**/*.rb'

# Gtk+ has a lot of accessor method starting with get_ or set_
Style/AccessorMethodName:
  Enabled: false

# Conform to old RuboCop behavior for now
Style/Alias:
  EnforcedStyle: prefer_alias_method

# Allow and/or for control flow only
Style/AndOr:
  EnforcedStyle: conditionals

# Dot at end of line makes it clearer that the line is not done
Style/DotPosition:
  EnforcedStyle: trailing

# FIXME: GirFFI uses a ffi-something naming scheme.
Style/FileName:
  Enabled: false

# Comment all the files!
Style/FrozenStringLiteralComment:
  EnforcedStyle: always

# Require at least two dependent lines before suggesting a guard clause
Style/GuardClause:
  MinBodyLength: 2

# Don't use if or unless as modifier if the line gets too long
Style/IfUnlessModifier:
  MaxLineLength: 60

# Multi-line assignment should be simply indented. Aligning them makes it even
# harder to keep a sane line length.
Style/MultilineOperationIndentation:
  EnforcedStyle: indented

# Multi-line method calls should be simply indented. Aligning them makes it
# even harder to keep a sane line length.
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Sometimes an if statement just looks better than next with a guard clause
Style/Next:
  Enabled: false

# TODO: See about has_ and have_
Style/PredicateName:
  NamePrefixBlacklist:
    - is_

# Allow explicit return with multiple return values
Style/RedundantReturn:
  AllowMultipleReturnValues: true

# Always use raise to raise exceptions
Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

# Accessors are only trivial if they match the ivar name.
# Also, allow accessors with ? in the name.
Style/TrivialAccessors:
  ExactNameMatch: true
  AllowPredicates: true

inherit_from: .rubocop_todo.yml
