$LOAD_PATH.unshift File.join(File.dirname(__FILE__), 'lib')
require 'girffi'
require 'girffi/builder'

#
# Test program using GirFFI builder, plus exploration of aditional needed
# methods etc. In the end, all code would have to be generated by the
# Builder, or be provided by a mixin.
#

builder = GirFFI::Builder.new
builder.build_module 'GObject'
builder.build_module 'Gtk'
builder.build_class 'Gtk', 'Window'

(my_len, my_args) = Gtk.init ARGV.length + 1, [$0, *ARGV]
p my_len, my_args
win = Gtk::Window.new(:toplevel)
win.show
GObject.signal_connect_data(win, "destroy", nil, nil, 0) { Gtk.main_quit }
Gtk.main
